"""add active column

Revision ID: 2762be5c1c08
Revises: af04e6b9faf2
Create Date: 2021-02-26 20:37:03.825194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2762be5c1c08'
down_revision = 'af04e6b9faf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'active')
    # ### end Alembic commands ###
