"""first migration

Revision ID: af04e6b9faf2
Revises: 
Create Date: 2021-02-21 11:45:57.383428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af04e6b9faf2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.Unicode(), nullable=True),
    sa.Column('event_filter', sa.Unicode(), nullable=True),
    sa.Column('url', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('subscriptions_idx_url_event_event_filter', 'subscriptions', ['event', 'event_filter', 'url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('subscriptions_idx_url_event_event_filter', table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
